config/routes.rb
Rails.application.routes.draw do
  root :to => 'pages#home'

  devise_for :users, :controllers => { registrations: 'registrations' }
  devise_scope :user do
    resources :users, only: [:index, :show], controller: 'registrations'
    put 'users/:id/remove_avatar', to: 'registrations#remove_avatar', as: 'remove_avatar'
    scope "/admin" do
      resources :users, only: [:show, :edit, :update, :destroy], as: 'admin_user'
      get 'users/:id/ban' => 'users#ban', as: 'ban_user'
    end
  end

end

app/models/user.rb
class User < ActiveRecord::Base

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_attached_file :avatar, styles: { large: "1024x1024>", medium: "300x300>", thumb: "50x50" }
   validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/

  def active_for_authentication?
    super && !banned?
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
  end

end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  def index
    @users = User.all.page params[:page]
  end

  def show
    @user = User.find params[:id]
  end

  def remove_avatar
    @user = User.find(params[:id])
    @user.avatar = nil
    @user.save
    redirect_to edit_user_registration_path, flash: { success: 'User profile avatar has been removed.' }
  end

  private

    def sign_up_params
      params.require(:user).permit(:name, :about, :avatar, :email, :password, :password_confirmation)
    end

    def account_update_params
      params.require(:user).permit(:name, :about, :avatar, :email, :password, :password_confirmation, :current_password)
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_filter :authenticate_admin
  before_action :load_user, only: [:edit, :update, :ban, :destroy]

  def edit
  end

  def update
    @user.update_attributes user_params
    render :edit
  end

  def ban
    @user.update_attributes banned: !@user.banned
    redirect_to :back
  end

  def destroy
    @user.destroy
    redirect_to :back
  end

  private

    def authenticate_admin
      if !current_user.try(:admin)
        flash[:notice] = "You should be an admin to access this URL"
        redirect_to root_path
      end
    end

    def load_user
      @user = User.find params[:id]
    end

    def user_params
      params.require(:user).permit(:name, :about, :avatar, :email, :password, :password_confirmation)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_navbar.html.haml
%nav.navbar.navbar-default{ role: "navigation" }
  .container
    .navbar-header
      - if current_user && current_user.avatar.file?
        = image_tag current_user.avatar.url(:thumb)
      %a.navbar-brand{ href: "/" } ProfilesApp
    .collapse.navbar-collapse.navbar-ex1-collapse
      %ul.nav.navbar-nav
        %li
          = link_to 'Users', '/users'
        - if !current_user
          %li.active
            = link_to 'Sign up', new_user_registration_path
          %li
            = link_to 'Log in', new_user_session_path
        - else
          %li
            = link_to 'Edit profile', edit_user_registration_path
          %li
            = link_to "Logout", destroy_user_session_path, method: :delete

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title ProfilesApp
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    = render 'layouts/navbar'

    .container
      - if notice || alert
        .notice
          - flash.each do |key, value|
            .bg-info
              = value

      = yield

app/views/pages/home.html.haml
%br/
%p.hello
  Hello, it's a HOME page of ProfilesApp :)

app/views/users/edit.html.haml
%h3 Edit user

= form_for @user, url: "/admin/users/#{@user.id}", html: { method: :put } do |f|
  - if @user.errors.any?
    .error_messages
      %p
        = pluralize(@user.errors.count, "error")
        prohibited this user from being saved:
      %ul
        - @user.errors.full_messages.each do |msg|
          %li.text-danger= msg

  .field
    = f.label :email
    %br/
    = f.email_field :email, autofocus: true
  .field
    = f.label :name
    %br/
    = f.text_field :name
  .field
    = f.label :about
    %br/
    = f.text_area :about, size: '100x5'

  .field
    - if @user.avatar.file?
      = image_tag @user.avatar.url(:thumb)
      = link_to 'Remove avatar', remove_avatar_path(@user.id), method: :put
    = f.file_field :avatar



  = f.submit "Save"